import { motion } from "framer-motion";
import { Sparkles, Cpu } from "lucide-react";

const ProductIntro = () => (
  <section className="section-padding bg-background">
    <div className="container max-w-3xl text-center">
      <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ duration: 0.6 }}>
        <h2 className="text-3xl md:text-4xl font-bold mb-6">What is CookMate?</h2>
        <p className="text-muted-foreground text-lg mb-10">
          CookMate is an AI-powered cooking assistant mobile application paired with a smart IoT cooking device. It personalises recipes based on your available ingredients, allergies, and preferences — then guides you step-by-step to a perfect meal.
        </p>
      </motion.div>
      <div className="grid sm:grid-cols-2 gap-6">
        {[
          { icon: Sparkles, title: "AI Recipe Engine", desc: "Get personalised recipes generated by AI based on what you have in your kitchen." },
          { icon: Cpu, title: "Smart IoT Device", desc: "An optional sensor that monitors stove temperature and alerts you in real-time." },
        ].map((item, i) => (
          <motion.div
            key={item.title}
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5, delay: i * 0.15 }}
            className="rounded-2xl bg-card border border-border p-6 text-left shadow-sm hover:shadow-md transition-shadow"
          >
            <div className="w-12 h-12 rounded-xl bg-primary/10 flex items-center justify-center mb-4">
              <item.icon className="text-primary" size={24} />
            </div>
            <h3 className="font-semibold text-lg mb-2">{item.title}</h3>
            <p className="text-muted-foreground text-sm">{item.desc}</p>
          </motion.div>
        ))}
      </div>
    </div>
  </section>
);

export default ProductIntro;
